name: DbEx

services:
  db-sql-server:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    
  db-mysql:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: "yourStrong#!Password"
    ports:
      - "3306:3306"

  db-postgres:
    build: ./.github/postgres
    image: dbex-postgres-test
    environment:
      POSTGRES_PASSWORD: "yourStrong#!Password"
    ports:
      - "5432:5432"