// <auto-generated />

/*
 * This file is automatically generated; any changes will be lost.
 */

#nullable enable

namespace DbEx.Test.Empty.Repositories;

public partial class TestDbContext
{
    /// <summary>
    /// Adds the generated models to the <paramref name="modelBuilder"/>.
    /// </summary>
    /// <param name="modelBuilder">The <see cref="Microsoft.EntityFrameworkCore.ModelBuilder"/>.</param>
    public void AddGeneratedModels(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
    {
        // Add the entity/model configuration for the [Test].[Contact] database table.
        modelBuilder.Entity<DbEx.Test.Empty.Persistence.Contact>(e =>
        {
            e.ToTable("Contact", "Test");
            e.HasKey(p => p.ContactId);
            e.Property(p => p.ContactId).HasColumnName("ContactId").HasColumnType("INT");
            e.Property(p => p.Name).HasColumnName("Name").HasColumnType("NVARCHAR(200)");
            e.Property(p => p.Phone).HasColumnName("Phone").HasColumnType("VARCHAR(15)");
            e.Property(p => p.DateOfBirth).HasColumnName("DateOfBirth").HasColumnType("DATE");
            e.Property(p => p.ContactTypeId).HasColumnName("ContactTypeId").HasColumnType("INT");
            e.Property(p => p.GenderId).HasColumnName("GenderId").HasColumnType("INT");
            e.Property(p => p.TenantId).HasColumnName("TenantId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Notes).HasColumnName("Notes").HasColumnType("NVARCHAR(MAX)");
            e.Property(p => p.ContactTypeCode).HasColumnName("ContactTypeCode").HasColumnType("NVARCHAR(50)");
        });

        // Add the entity/model configuration for the [Test].[Person] database table.
        modelBuilder.Entity<DbEx.Test.Empty.Persistence.Person>(e =>
        {
            e.ToTable("Person", "Test");
            e.HasKey(p => p.PersonId);
            e.Property(p => p.PersonId).HasColumnName("PersonId").HasColumnType("UNIQUEIDENTIFIER");
            e.Property(p => p.Name).HasColumnName("Name").HasColumnType("NVARCHAR(200)");
            e.Property(p => p.NicknamesJson).HasColumnName("NicknamesJson").HasColumnType("NVARCHAR(500)");
            e.Property(p => p.Address).HasColumnName("AddressJson").HasColumnType("NVARCHAR(500)").HasConversion(new Persistence.JsonConverter<Persistence.Address?>());
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)").ValueGeneratedOnUpdate();
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET").ValueGeneratedOnUpdate();
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)").ValueGeneratedOnAdd();
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET").ValueGeneratedOnAdd();
        });
    }
}

#nullable restore