CREATE TABLE [Test].[Status] (
    [StatusId] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWSEQUENTIALID()) PRIMARY KEY,
    [Code] NVARCHAR (50) NOT NULL,
    [Text] VARCHAR (256) NOT NULL,
    [CreatedBy] NVARCHAR(250) NULL,
    [CreatedOn] DATETIMEOFFSET NULL,
    [UpdatedBy] NVARCHAR(250) NULL,
    [UpdatedOn] DATETIMEOFFSET NULL,
    [TenantId] NVARCHAR(50) NOT NULL,
    UNIQUE ([TenantId], [Code])
)