// <auto-generated />

/*
 * This file is automatically generated; any changes will be lost.
 */

#nullable enable

namespace DbEx.Test.Empty.Persistence;

/// <summary>
/// Persistence model representing the '<c>[Test].[Contact]</c>' database table.
/// </summary>
public partial class Contact
{
    /// <summary>
    /// Gets or sets the value of the '<c>ContactId</c>' column (<c>INT</c>).
    /// </summary>
    /// <remarks>This is the primary key.</remarks>
    public int ContactId { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>Name</c>' column (<c>NVARCHAR(200)</c>).
    /// </summary>
    public string Name { get; set; } = default!;

    /// <summary>
    /// Gets or sets the value of the '<c>Phone</c>' column (<c>VARCHAR(15) NULL</c>).
    /// </summary>
    public string? Phone { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>DateOfBirth</c>' column (<c>DATE NULL</c>).
    /// </summary>
    public DateOnly? DateOfBirth { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>ContactTypeId</c>' column (<c>INT</c>).
    /// </summary>
    public int ContactTypeId { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>GenderId</c>' column (<c>INT NULL</c>).
    /// </summary>
    public int? GenderId { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>TenantId</c>' column (<c>NVARCHAR(50) NULL</c>).
    /// </summary>
    public string? TenantId { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>Notes</c>' column (<c>NVARCHAR(MAX) NULL</c>).
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>ContactTypeCode</c>' column (<c>NVARCHAR(50) NULL</c>).
    /// </summary>
    public string? ContactTypeCode { get; set; }
}

#nullable restore