// <auto-generated/>

/*
 * This file is automatically generated by 'DbEx.Test.Console'; any changes will be lost.
 */

#nullable enable

namespace DbEx.Test.Empty.Persistence;

/// <summary>Persistence model representing the '<c>[Test].[ExtraTypes]</c>' database table.</summary>
public partial class ExtraTypes
{
    /// <summary>Gets or sets the value of the '<c>ExtraTypesId</c>' column (<c>INT</c>).</summary>
    /// <remarks>This is the primary key.</remarks>
    public int ExtraTypesId { get; set; }

    /// <summary>Gets or sets the value of the '<c>Location</c>' column (<c>GEOGRAPHY NULL</c>).</summary>
    public Geometry? Location { get; set; }

    /// <summary>Gets or sets the value of the '<c>Shape</c>' column (<c>GEOMETRY NULL</c>).</summary>
    public Geometry? Shape { get; set; }

    /// <summary>Gets or sets the value of the '<c>Path</c>' column (<c>HIERARCHYID NULL</c>).</summary>
    public HierarchyId? Path { get; set; }

    /// <summary>Gets or sets the value of the '<c>Document</c>' column (<c>XML NULL</c>).</summary>
    public string? Document { get; set; }

    /// <summary>Gets or sets the value of the '<c>Embedding</c>' column (<c>VECTOR(3) NULL</c>).</summary>
    public SqlVector<float>? Embedding { get; set; }

    /// <summary>Gets or sets the value of the '<c>Variant</c>' column (<c>SQL_VARIANT NULL</c>).</summary>
    public object? Variant { get; set; }

    /// <summary>Gets or sets the value of the '<c>Payload</c>' column (<c>JSON NULL</c>).</summary>
    public string? Payload { get; set; }
}

#nullable restore