// <auto-generated />

/*
 * This file is automatically generated; any changes will be lost.
 */

#nullable enable

namespace DbEx.Test.Empty.Persistence;

/// <summary>
/// Persistence model representing the '<c>[Test].[Person]</c>' database table.
/// </summary>
public partial class Person
{
    /// <summary>
    /// Gets or sets the value of the '<c>PersonId</c>' column (<c>UNIQUEIDENTIFIER</c>).
    /// </summary>
    /// <remarks>This is the primary key.</remarks>
    public Guid PersonId { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Gets or sets the value of the '<c>Name</c>' column (<c>NVARCHAR(200)</c>).
    /// </summary>
    public string Name { get; set; } = default!;

    /// <summary>
    /// Gets or sets the value of the '<c>NicknamesJson</c>' column (<c>NVARCHAR(500) NULL</c>).
    /// </summary>
    public string? NicknamesJson { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>AddressJson</c>' column (<c>NVARCHAR(500) NULL</c>).
    /// </summary>
    public Persistence.Address? Address { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>CreatedBy</c>' column (<c>NVARCHAR(250) NULL</c>).
    /// </summary>
    public string? CreatedBy { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>CreatedOn</c>' column (<c>DATETIMEOFFSET NULL</c>).
    /// </summary>
    public DateTimeOffset? CreatedOn { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>UpdatedBy</c>' column (<c>NVARCHAR(250) NULL</c>).
    /// </summary>
    public string? UpdatedBy { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>UpdatedOn</c>' column (<c>DATETIMEOFFSET NULL</c>).
    /// </summary>
    public DateTimeOffset? UpdatedOn { get; set; }
}

#nullable restore